use_frameworks!

platform :ios, '9.0'

target 'HMInputBarAccessoryView_Example' do
  pod 'HMInputBarAccessoryView', :path => '../'

  target 'HMInputBarAccessoryView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
